version: '3.8'

services:
  postgres:
    image: postgis/postgis:latest
    container_name: uber_database
    restart: always
    environment:
      POSTGRES_DB: uber
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
